ladybug-tools/honeybee-core

dev-requirements.txt, setup.py
As discussed today I changed the dependency from `ladybug-geometry` to `lbt-ladybug`. With this change all the libraries that are using `honeybee-core` will also have access to `ladybug-core` features.
This will fix the currently failing tests for honeybee-radiance:
https://travis-ci.org/ladybug-tools/honeybee-radiance/jobs/543996323
=> fix(dependencies): update dependency to ladybug-core

honeybee/face.py, honeybee/typing.py
This adds the typing module to honeybee core as we discussed @mostaphaRoudsari .  I also set the name of the honeybee Face to use the type checking such that it is always valid for both E+ and Radiance.
Note that, with this implementation, an error will be raised for all honeybee face names that exceed 100 characters after stripping out illegal characters.  I don't know if we should be adding an extra setter for `name_original` so that we can set this to be the crazy-long Revit name if we so desire. Just let me know if you think we should have a separate setter and I can add it.
=> feat(typing): Adding a module to assist with type checking

README.md, honeybee/_lockable.py, honeybee/aperture.py, honeybee/aperturetype.py, honeybee/boundarycondition.py, honeybee/door.py, honeybee/face.py, honeybee/facetype.py, honeybee/model.py, honeybee/properties.py, honeybee/room.py, honeybee/shade.py, honeybee/typing.py, tests/aperture_test.py, tests/aperturetype_test.py, tests/boundary_condition_test.py, tests/door_test.py, tests/face_test.py, tests/facetype_test.py, tests/lockable_test.py, tests/room_test.py, tests/shade_test.py, tests/typing_test.py
This PR is fleshing out the key objects that make up honeybee-core and lays down a lot of rules for how they interact with one another. I am only submitting this as a draft PR since I don't think it's worthwhile to write all of the tests until @mostaphaRoudsari has gotten the chance to review it (I am anticipating some feedback that will result in changes).
Over the course of fleshing everything out, I came to a couple of realizations/limitations of using `weakref.proxy` that have some important implications for the core library (assuming we want to continue using it):
1) Because all of the variables that exist within a given method on a class are garbage collected after the method is run (except for the returned variables), we will not be able to implement methods that automatically …
=> feat(objects): Adding objects for zone, aperture, and door

honeybee/properties.py
Very minor tweak to the duplicate_extension_attr method that all honeybee-core properties objects share.  The tweak ensures that the properties added by extensions are correctly duplicated.  It also includes a slight performance improvement by catching properties that should not be duplicated before they go into a try/except loop to duplicate them.
=> fix(properties): Ensuring extension properties are correctly duplicated

.github/project-manager.yml
This PR is copied across a bunch of repositories to set up a global kanban to manage triage, backlog and issue progress for multiple repositories as well as enable a Hacktoberfest board to help people navigate and find issue they might want to help with.
=> chore(project manager): add basic + hacktoberfest config

honeybee/_base.py, honeybee/_basewithshade.py, honeybee/aperture.py, honeybee/boundarycondition.py, honeybee/door.py, honeybee/face.py, honeybee/model.py, honeybee/room.py, honeybee/shade.py, tests/aperture_test.py, tests/door_test.py, tests/face_test.py, tests/room_test.py, tests/shade_test.py
I know that multipliers clearly have a use in energy simulation but, after thinking about it, they are just as helpful in computing daylight metrics over buildings and so they really should live in honeybee-core. So this commit adds them as a property on the room.
I also took the opportunity to revise several of the docstrings to make it clear which core properties are set-able or not (following a convention that I originally saw in RhinoCommon). You don't really have to review these though, @mostapharoudsari . Just looking over the Room changes and letting me know if you agree is good.
=> feat(room): Add property for Room multiplier

honeybee/aperture.py, honeybee/door.py, honeybee/face.py, honeybee/model.py, honeybee/room.py, honeybee/shade.py, honeybee/writer.py, honeybee/writer/__init__.py, honeybee/writer/aperture.py, honeybee/writer/door.py, honeybee/writer/face.py, honeybee/writer/model.py, honeybee/writer/room.py, honeybee/writer/shade.py, tests/aperture_test.py, tests/door_test.py, tests/face_test.py, tests/model_test.py, tests/room_test.py, tests/shade_test.py
As we had it previously, there was no way to specify a separate writer for Rooms vs. Faces vs. Apertures, etc. This commit addresses this limitation by adding distinct classes under the `writer` module for each geometry object. A property under each writer that lists the `availabe_formats` to which objects can be written has also been added.
=> feat(writer): Break down writers for individual geometry objects

honeybee/face.py, honeybee/room.py, tests/room_test.py
After deliberating a bit on different ways to do this, it seems best to just return the information about the adjacencies that were found during the solve_adjacency run. This way, the information can be used to assign custom properties to the newly-adjacent faces, apertures and doors. For example, assigning custom interior materials/constructions or setting all new adjacent faces to be air walls.
=> feat(adjacency): Output adjacency information from solve_adjacency

honeybee/room.py
I am just making a style change here for a single line of code, which helps with some dragonfly-core features I am working on now. So I am just going to merge this one in.
=> frat(from_polyface): Improve naming convention in Room.from_polyface

honeybee/aperture.py, honeybee/door.py, honeybee/face.py, honeybee/room.py, honeybee/shade.py, tests/room_test.py
I can see that this improves the speed of the calculation to more than double what it was previously. Given this, I think we should definitely implement some type of bounding box check on the intersect masses workflows.
=> feat(room): Add bounding box check to solve adjacency

honeybee/_base.py, honeybee/_basewithshade.py, honeybee/aperture.py, honeybee/face.py, honeybee/room.py, tests/aperture_test.py, tests/face_test.py, tests/room_test.py
This method will ease the cases where someone duplicates and edits a starting object and then wants to combine it with the original object into one Model (like making a model of repeated rooms) since all objects within a Model must have unique names.
=> feat(rename): Add rename method to all objects

honeybee/_base.py, honeybee/aperture.py, honeybee/boundarycondition.py, honeybee/door.py, honeybee/face.py, honeybee/shade.py
I realized that the original method will not work as intended unless the prefix is also added to Surface boundary condition objects. This should not make it possible to duplicate objects, add a prefix, and then not have to re-solve adjacency before adding them to a Model.
=> fix(add_prefix): Add the prefix to Surface boundary conditions

honeybee/aperture.py, honeybee/door.py, honeybee/face.py, honeybee/orientation.py, honeybee/room.py, tests/orientation_test.py
This new module constitutes all of the generic functions for assigning different properties based on Face or Aperture orientation.  I imagine that these will get applied all over honeybee and its extensions given how useful this type of automation is. And I know @mostapharoudsari mentioned in an earlier review that he felt these functions belonged in the core rather than repeated over several components.
=> feat(orientation): Add module to handle orientation subdivision

MANIFEST.in, honeybee/config.json, honeybee/config.py, setup.py, tests/config_test.py
The config file handles several commonly-accessed folders including the folders for the default simulation folder and the location where the python exe is installed.
=> feat(config): Add module and json to handle configurations

honeybee/config.py
From my understanding, I think this code is less prone to errors and I have verified that it works on both Windows and Mac.
=> style(config): Implement cleaner way to find default_simulation_folder

honeybee/aperture.py, honeybee/door.py, honeybee/face.py, honeybee/properties.py, honeybee/room.py, honeybee/shade.py
The recent shift in the setup of HVAC systems has created a new situation that I am sure will arise again in the future. Specifically, when a user wants to change the name of an object and all of its sub-objects (like after duplicating and moving a Room to combine it with the original Room into one Model), there are also some extension attributes that should be renamed (like single-room HVAC systems). This commit adds in code to call such add_prefix methods on extension attributes if the method exists. If the method does not exist, the renaming process simply proceeds as usual.
=> feat(add_prefix): Include option to add prefix to extension attributes

honeybee/_basewithshade.py, honeybee/aperture.py, honeybee/config.py, honeybee/door.py, honeybee/extensionutil.py, honeybee/face.py, honeybee/model.py, honeybee/orientation.py, honeybee/properties.py, honeybee/room.py, honeybee/shade.py, tests/aperture_test.py, tests/door_test.py, tests/face_test.py, tests/shade_test.py
This is_indoor property is needed to correctly set up the ModifierSet on honeybee-radiance.
Also, as part of this commit, I am adding the ability to assign Shades to Doors. This has now come up enough times from more than one person that I've realized that I better implement it now while I still have a near-complete idea of all the other repositories affected by the change (another month or two and I don't think that I would be able to catch all of the places that will be incorrect as a result of this change). As far as I can tell, the following repos need to be changed with a PR that parallels this one:
* honeybee-energy (especially the Model objectand Model writer)
* honeybee-schema (including both Door schema and the Wiki)
* energy-model-measure (OpenStudio has no concept of assigning …
=> feat(shade): Add property to track whether Shade is on the indoors

honeybee/altnumber.py, honeybee/boundarycondition.py, honeybee/facetype.py, tests/boundary_condition_test.py
This commit brings the library up-to-date with these recent changes in honeybee-schema:
https://github.com/ladybug-tools/honeybee-schema/pull/44
Only the to_dict methods have been changed and the Python objects still internally use strings for simplicity. An alternative approach could use classes for AutoCalculate, AutoSize and NoLimit and use them similarly to how the `facetype` module is used. A change like this would involve a bunch of edits in a lot of different places, though. @mostapharoudsari, what do you think?
=> fix(boundarycondition): Update based on recent schema change

honeybee/aperture.py, honeybee/door.py, honeybee/face.py, honeybee/model.py, honeybee/room.py, honeybee/shade.py, tests/model_test.py
This commit allows people creating Model objects to store the units system and tolerance on the Model itself. The aim of this is that, by specifying these values here, users don't need to worry about tedious geometry checks when they create dictionaries they want to serialize into Models. We can also use this to automatically scale the model to meters before export to EnergyPlus.
=> feat(model): Add properties for units and tolerance

docs/_static/custom.css, docs/_templates/layout.html, docs/conf.py, honeybee/_base.py, honeybee/_basewithshade.py, honeybee/_lockable.py, honeybee/aperture.py, honeybee/boundarycondition.py, honeybee/door.py, honeybee/extensionutil.py, honeybee/face.py, honeybee/model.py, honeybee/orientation.py, honeybee/properties.py, honeybee/room.py, honeybee/search.py, honeybee/shade.py
Hi @chriswmackey 
This time I found these error messages when I generated the pages.  
honeybee - ERROR - Failed to import honeybee_energy!
Traceback (most recent call last):
File "C:\Users\sgara\Documents\GitHub\honeybee-core\honeybee\__init__.py", line 16, in <module>
extensions[name] = importlib.import_module(name)
File "c:\python27\lib\importlib\__init__.py", line 37, in import_module
__import__(name)
File "c:\python27\lib\site-packages\honeybee_energy\__init__.py", line 8, in <module>
import honeybee_energy._extend_honeybee
File "c:\python27\lib\site-packages\honeybee_energy\_extend_honeybee.py", line 19, in <module>
from .properties.model import ModelEnergyProperties
File "c:\python27\lib\site-packages\honeybee_energy\properties\model.py", line 5, in <module>
from …
=> Format docstrings for correct display in sphinx-generated bootstrap pages 

honeybee/config.py
I think it will help to add a little more hierarchy to the HOME/honeybee/ folder now that I see we want to keep the default standards data there. So I'm changing the default simulation folder to be HOME/honeybee/simulation/
=> feat(config): Organize default simulation folder

honeybee/_basewithshade.py, honeybee/_lockable.py, honeybee/aperture.py, honeybee/boundarycondition.py, honeybee/cli/validate.py, honeybee/colorobj.py, honeybee/dictutil.py, honeybee/door.py, honeybee/extensionutil.py, honeybee/face.py, honeybee/model.py, honeybee/orientation.py, honeybee/properties.py, honeybee/room.py, honeybee/search.py, honeybee/shade.py, honeybee/typing.py, honeybee/writer/__init__.py
This commit adds methods that allow extension attributes that are geometric to be transformed whenever their host is transformed.  These methods work by searching through the extension attributes and, if they find an extension that has the given transform method implemented (eg, move, rotate, scale), it will perform that transform whenever the host is transformed.
This is a necessary precursor to adding attributes to honeybee-radiance that include geometry (like dynamic shades that can be applied to specific radiance states). So, now, if someone moves a Room, the dynamic shades in the radiance properties of the Room's apertures are also moved.
@mostapharoudsari will also be very happy to see that the spell-checker is being put to good use.
=> feat(transform): Ensure extension properties are transformed with host

honeybee/model.py, setup.py, tests/model_test.py, tests/shade_test.py
This will be particularly useful in honeybee-radiance workflows where we need to distinguish between indoor and outdoor shades in the Model radiance folder.
=> feat(model): Add indoor_shades and outdoor_shades to Model

honeybee/model.py, requirements.txt, tests/model_test.py
After some discussions with @mostapharoudsari , we have decided that the north should not be a property of the Model for the same reason why we don't have the location as a part of the model. The north direction is a property of the simulation assets like the skies used in Radiance or the simulation parameters used in our EnergyPlus.
=> fix(model): Remove north from Model properties

honeybee/properties.py
This effectively means that supplying `None` for an extension key is the same as not including the key at all.  I will send similar PRs to honeybee-schema, dragonfly-core, and dragonfly-schema.
=> fix(properties): Allow null values when extensions are not used

honeybee/extensionutil.py
This way, users don't have to specify properties for individual geometry objects if they are ok with the default.
Resolves https://github.com/ladybug-tools/honeybee-core/issues/125
=> fix(extensionutil): Handle the case of missing extension keys

requirements.txt
Since we are planning to turn lbt-ladybug into a package that installs ladybug along with all of its extensions.
=> fix(pypi): Update dependency to reference ladybug-core

honeybee/config.py
This commit changes the folders.python_exe_path to be the one that should be used for CLI calls. So it looks first for a ladybug_Tools installation before deciding to return sys.executable.
=> fix(config): Search for Python executable in ladybug_tools

honeybee/aperture.py, honeybee/door.py, honeybee/face.py
The way the Face.from_dict() method was originally written, the checks to ensure that child faces have the same normal as their parent face were not occurring.
This makes sure that this check happens and it still does the check to make sure that Ground or Adiabatic BCs aren't assigned to Faces with Apertures or Doors.
=> fix(face): Fix sub-face normal correction upon re-serialization

honeybee/config.py
This will be necessary for calling PYthon executables in a cross-platform way.
Resolves https://github.com/ladybug-tools/honeybee-core/issues/203
=> fix(config):  Add a config variable for the path to Python scripts

honeybee/room.py
I realized that the fact that the average_floor_height returns None when there are no floors makes it very difficult to group Rooms by floor height to auto-generate stories.
So this commit changes this property to return the Room min Z when there are no floors.
=> fix(room): Implement better default for floor_height with no floors

honeybee/aperture.py, honeybee/door.py, honeybee/face.py, honeybee/model.py, honeybee/room.py, honeybee/shade.py
The check that we have to flip the orientation of Faces to ensure they point outwards from a Room was not also performing a check for whether there were sub-faces that needed to be flipped.
This commit fixes this issue.
=> fix(room): Flip sub-faces as part of orientation checks

honeybee/_basewithshade.py, honeybee/shade.py, tests/aperture_test.py, tests/shade_test.py
This property is False by default but can be set to True by the user. When a Shade is assigned as a child of another object, it is automatically set to False.
=> feat(shade): Add is_detached property to Shade

dev-requirements.txt, honeybee/cli/__init__.py, honeybee/cli/create.py, honeybee/cli/edit.py, honeybee/cli/validate.py, honeybee/room.py, setup.py, tests/cli_create_test.py, tests/cli_edit_test.py, tests/cli_validate_test.py, tests/room_test.py
This commit adds two new groups for creating models  and editing their geometry.
The create group houses methods for creating model JSONs for typical geometry cases like shoe boxes, rectangles and (eventually), regular polygons, L and H-shaped plans, etc.
The edit group houses methods for solving adjacency, converting units, generating windows by ratio, generating overhangs.
=> feat(cli): Add groups for creating and editing models

honeybee/aperture.py, honeybee/cli/create.py, honeybee/cli/edit.py, honeybee/face.py, tests/aperture_test.py, tests/cli_create_test.py, tests/cli_edit_test.py, tests/face_test.py
This commit adds commands to add extruded borders and various types of louvers.
I also added a max_count option to the louvers by distance methods, which I think a lot of people will appreciate in order to generate light-shelf-like louvers.
LAstly, I'm changing the default WWR for the shoe box to be 0 so that it can better integrate with the edit methods that assign specific window and shade geometries.
=> feat(cli): Add more commands to generate different types of shades

dev-requirements.txt, requirements.txt, setup.py
As it is set up right now ladybug-geometry-polyskel doesn't get installed with the requirements. As a result the test for honeybee-radiance and honeybee-energy cli fails. Add it to the main requirements fixes the issue.
https://travis-ci.org/github/ladybug-tools/honeybee-radiance/jobs/736251292#L1438
https://travis-ci.org/github/ladybug-tools/honeybee-energy/jobs/736142705#L6159
=> fix(dep): move ladybug-geometry-polyskel to requirements

honeybee/_base.py
I originally had the property as read only in order to prevent the many cases where setting the identifier will break existing references across objects. But I think I have just come to realize that I can't stop people from playing with fire if they want to.  I guess people should be aware that re-setting a unique ID can have unintended consequences unless they know that they are doing.
=> fix(identifier): Allow identifier to be set by the user

honeybee/model.py, honeybee/search.py, tests/model_test.py, tests/search_test.py
It finally dawned on my why the search behavior wasn't working as I expected. Normally, more search terms should mean a narrower set of results. Now I only choose the boolean intersection of the search terms instead of the boolean union.
=> fix(search): Change search behavior to get more specific with more terms

requirements.txt
I am getting rid of the == operator in the dependency versions  just for the CI so that we don't always get the tests failing every time we make a change to ladybug-geomtery.
=> fix(ci): Loosen requirements in CI so that pip stops breaking things

honeybee/config.py, honeybee/logutil.py
It seems parallel luigi tasks can cause race conditions with certain operations like creating default simulation folders.  These try/excepts should catch these cases now.
=> fix(config): Add try/except to catch potential race conditions

honeybee/model.py
It seems that the luigi process under the hood does not use file extensions (or overwrites them to whatever the function template is). So we will need a careful way to sense the file type without loading the whole file into memory. From what I can tell, sensing the { at the start of a JSON should be a safe bet.
=> fix(model): Handle the case of missing file extension

honeybee/cli/create.py, honeybee/cli/edit.py, tests/cli_create_test.py
This is the default on the current model object and it makes sense to do the same with the CLI commands.
=> fix(cli): Have default model tolerance set by units system

honeybee/aperture.py, honeybee/door.py
This will enable workflows where someone just moves an Aperture or Door but leaves the parent Face unaltered.
=> fix(subface): Ensure parent geometry is reset after transform

honeybee/cli/validate.py
The error messages of the core libraries are just so much clearer than those from Pydantic. So I am changing the model validation to do serialization with the core libraries first and only run the Pydantic validation at the end.
=> fix(validate): Have validation use core libraries before Pydantic

honeybee/room.py
I realized that the method might not be so reliable for concave faces where the center point lies outside of the face boundary.
So I am changing it to use the exact ladybug_geometry method that gets called in the solve adjacency method, which ensure that we always get a point that is on the face.
=> style(room): Ensure faces_by_guide_surface works with concave faces

honeybee/_basewithshade.py, honeybee/aperture.py, honeybee/door.py, honeybee/face.py, honeybee/model.py, honeybee/room.py, honeybee/shade.py, tests/aperture_test.py, tests/door_test.py, tests/face_test.py, tests/model_test.py, tests/room_test.py, tests/shade_test.py
Now, people will not get the self-interesting error if it's because the Face contains a duplicate vertex.
Also, the error messages will contain the Room ID.
=> fix(validate): Improve the self-intersection check

honeybee/dictutil.py, honeybee/typing.py, tests/typing_test.py
I imagine that we will use this throughout the extensions to give better error messages about invalid objects.
=> fix(typing): Add method to raise informative serialization errors

honeybee/boundarycondition.py, honeybee/cli/edit.py, honeybee/face.py, honeybee/model.py, honeybee/room.py
This new method is more reliable at ensuring adjacent Faces have matching numbers of vertices whenever there are duplicated colinear vertices.
The commit also improves the adjacency validation check so that it not only catches cases of mismatched areas but also different shapes within the tolerance.
=> fix(room): Add more reliable method to clean envelope geometry

honeybee/model.py
Thanks to the E+ developers, there is no longer a need to perform this Validation check:
https://github.com/NREL/EnergyPlus/pull/9855
=> fix(model): Remove validation check for all Air-Boundary Rooms

honeybee/room.py
I'm going to make use of this in Dragonfly and I thought about having Dragonfly extend the honeybee Room class but I think it's just much simpler and more efficient this way. I might also make use of it in other cases where I need to keep track of a particular building that the honeybee Room is apart of.
=> fix(room): Add a hidden property for Room._parent

honeybee/room.py
This takes advantage of the fact that we can now snap several polygons to one another and boolean union them all together at once.
This commit also removes an extra check that has now been integrated into the underlying ladybug-geometry method.
=> fix(room): Improve the methods that computes horizontal boundary

honeybee/model.py, honeybee/room.py
I'm also taking the opportunity to add an output to the `reset_ids()` method, which will help with mapping other parts of the model after this method is run.
=> fix(room): Ensure that vertex sizes always match when cleaning envelope

honeybee/aperture.py, honeybee/door.py, honeybee/face.py, honeybee/room.py
This includes ignoring degenerate holes in Face3D and adding a new validation error that will specifically call out degenerate Faces, Apertures Doors, rather than calling the whole Room volume degenerate.
=> fix(validate): Improve the validation of degenerate geometry

honeybee/typing.py
It seems much more preferable to just use a unique but consistent ID in this case so people do not get blocked.
=> fix(typing): Don't raise exception when no legal characters are provided
