- honeybee/typing.py
Add two new types that I needed for honeybee-radiance and refactored the code for current methods.
The main change is that I relaxed integer methods to accept string float inputs (e.g. '1.1', '0.1').
> feat(typing): add normpath and wrapper

- .coveragerc
- honeybee/_base.py
- honeybee/_basewithshade.py
- honeybee/aperture.py
- honeybee/aperturetype.py
- honeybee/boundarycondition.py
- honeybee/door.py
- honeybee/extensionutil.py
- honeybee/face.py
- honeybee/facetype.py
- honeybee/model.py
- honeybee/properties.py
- honeybee/room.py
- honeybee/shade.py
- tests/aperture_test.py
- tests/boundary_condition_test.py
- tests/door_test.py
- tests/face_test.py
- tests/model_test.py
- tests/room_test.py
- tests/shade_test.py
This commit also includes edits to the other geometry objects in order to be able to support the use of to_dict methods to generate the Model schema.
@mostaphaRoudsari ,
The code edits here are ready to be reviewed, though I'll still be adding more tests for the Model object over the next day.
> feat(model): Adding to_dict and from_dict to Model

- .releaserc.json
- .travis.yml
- deploy.sh
- dev-requirements.txt
- requirements.txt
- setup.py
> ci(docs): build docs in seperate step to PyPi deployment

- .travis.yml
I was distracted by versioning and didn't notice this error.
> ci(docs): fix sphinx command

- honeybee/cli.py
- honeybee/logutil.py
> fix(logger): write log file to home folder

- honeybee/boundarycondition.py
- tests/boundary_condition_test.py
... and add tests to catch these cases.
> fix(boundarycondition): Fix bugs in custom boundary conditions

- .travis.yml
- honeybee/logutil.py
- honeybee/properties.py
- honeybee/room.py
I hope it's ok that I also turned coveralls on for this repo with this PR. I know it can be annoying and we can turn it off at some point if it irritates people.  I just want to get a sense of where we currently stand with coverage and which lines of code are not tested.
> docs(properties): Add documentation to hidden properties methods

- honeybee/aperture.py
- honeybee/face.py
- honeybee/room.py
- tests/model_test.py
- tests/room_test.py
Just a few small tweaks to naming in this one. It shouldn't affect anything in other repos.
> style(naming): Fix typos and changed naming of some methods

- honeybee/extensionutil.py
- honeybee/search.py
- tests/aperture_test.py
- tests/door_test.py
- tests/face_test.py
- tests/model_test.py
- tests/room_test.py
- tests/search_test.py
- tests/shade_test.py
- tests/typing_test.py
.. I also fixed some of the tests that were in the previous commit about writers such that these tests will still pass when someone has a honeybee extension installed.
> feat(search): Add utilities for searching arrays by keyword

- README.md
Sorry for using the feat tag here for something small but I have to trigger another release.
> feat(Readme): Improve Readme

- honeybee/aperture.py
- honeybee/face.py
In accordance with the recent bug fixes to ladybug_geometry's contour methods, this commit brings honeybee in line with the new inputs to these methods.
> fix(louvers): Fix louver-generating methods to match ladybug_geometry

- honeybee/model.py
- tests/model_test.py
This will be helpful for easily converting the model to different units systems in various CLI calls
> feat(model): Add convert_to_units to Model

- honeybee/config.py
- honeybee/dictutil.py
- tests/dictutil_test.py
This will be useful in cases where we aren't sure what type of object we are re-serializing.
> feat(dictutil): Add module to re-serialize any object from a dictionary

- honeybee/colorobj.py
- honeybee/search.py
- tests/colorobj_test.py
This commit adds a module and two objects to color rooms with their attributes and color faces/sub-faces with their attributes.
I should add some tests before I merge this in.
> feat(colorobj): Add module to color geometry with its attributes

- honeybee/_base.py
- honeybee/_basewithshade.py
- honeybee/aperture.py
- honeybee/boundarycondition.py
- honeybee/colorobj.py
- honeybee/door.py
- honeybee/face.py
- honeybee/model.py
- honeybee/properties.py
- honeybee/room.py
- honeybee/shade.py
- honeybee/typing.py
- tests/aperture_test.py
- tests/boundary_condition_test.py
- tests/colorobj_test.py
- tests/dictutil_test.py
- tests/door_test.py
- tests/face_test.py
- tests/json/nonascii_face.json
- tests/model_test.py
- tests/room_test.py
- tests/shade_test.py
- tests/typing_test.py
This is the first of a series of commits to 12 repos that change the name property to uuid.
This PR should NOT be merged in until comparable PRs can be put together for the other 12 repos that are broken by this change.
> refactor(identifier): Change name property to identifier

- honeybee/face.py
- tests/face_test.py
This method will be useful for generating skylights based on a ratio.
> feat(face): Add apertures_by_ratio_gridded method

- honeybee/room.py
- requirements.txt
- tests/room_test.py
This is cleaner in that it always returns a single mesh for the room.
> feat(room): Include mesh joining in Room.generate_grid

- honeybee/model.py
- honeybee/room.py
- tests/model_test.py
- tests/room_test.py
This commit adds a story property to honeybee-core Rooms and add a staticmethod to auto-assign stories based on floor heights.
Resolves https://github.com/ladybug-tools/honeybee-core/issues/106
> feat(room): Add story property to Room

- honeybee/_base.py
- honeybee/altnumber.py
- honeybee/aperture.py
- honeybee/boundarycondition.py
- honeybee/cli/__init__.py
- honeybee/cli/validate.py
- honeybee/colorobj.py
- honeybee/config.py
- honeybee/door.py
- honeybee/face.py
- honeybee/facetype.py
- honeybee/model.py
- honeybee/orientation.py
- honeybee/room.py
- honeybee/shade.py
- honeybee/typing.py
- tests/aperture_test.py
- tests/door_test.py
- tests/face_test.py
- tests/room_test.py
- tests/shade_test.py
This will be particularly helpful in energy simulation workflows.
I also fixed a number of Flake8 styling issues.
> feat(geometry): Add methods to remove co-linear vertices

- honeybee/config.py
- honeybee/model.py
This commit adds a property to the config.Folders class to get the version of honeybee-schema if it was installed alongside honeybee-core from PyPI.  This version number then gets written into the Model dictionary.
> feat(model): Sense honeybee-schema version and write it into Model dict

- honeybee/typing.py
- tests/typing_test.py
@chriswmackey 
Here are the 3 new float_in_range checks I added to check variable inclusive/exclusive ranges, required for the AFN.
Sorry for not assigning reviewers, and assignees, looks like I don't have access to this repo.
Let me know how it looks. 
S
> feat(typing): Add 3 new float range checks to typing.

- honeybee/checkdup.py
- honeybee/cli/validate.py
- honeybee/dictutil.py
- honeybee/model.py
- tests/model_test.py
This commit adds a few more checks into the Model validation command.  It also separates the duplicate identifier-checking into its own module that can be used in extensions.
Resolves https://github.com/ladybug-tools/honeybee-core/issues/198
> fix(cli): Improve Model validation command

- dev-requirements.txt
- honeybee/cli/__init__.py
- honeybee/config.py
- tests/cli_test.py
This commit adds a `honeybee config` command that returns a full JSON of configuration variables, including the version of Python.
> feat(config): Add Python version check and add config command 

- honeybee/cli/create.py
... and I'm getting rid of the import statements on unused modules.
> style(cli): improve docstrings of create module

- cli-requirements.txt
- setup.py
taking out extra requirements from setup.py
> chore(deps-cli): add cli-requirements file

- honeybee/model.py
- tests/model_test.py
- tests/room_test.py
This will make it easier to apply the prefix method broadly on the interface end.
> fix(model): Add an add_prefix method to Model

- honeybee/model.py
- tests/model_test.py
Added a classmethod to make it easier to load hbjson files.
> fix(model): add from_hbjson method

- honeybee/model.py
- tests/model_test.py
This will be extremely helpful for large models that max out memory when they load as JSON.
> feat(model): Add methods to serialize to/from pickle

- docs/cli.rst
- docs/cli/index.rst
- docs/conf.py
- docs/index.rst
- requirements.txt
Hi @chriswmackey,
This one looks pretty straightforward, no warnings or special cases. Please let me know if you have any issue on your side!
> docs(cli): Improve CLI documentation structure

- honeybee/face.py
- honeybee/room.py
This effectively abstracts out the logic used in the ground_by_custom_surface method so that we can use it to set other properties if we want.
> fix(room): Add a method to select faces using a guide surface

- dev-requirements.txt
We already get it with ladybug-core
> chore(deps-dev): Remove unnecessary click

- honeybee/_basewithshade.py
- honeybee/aperture.py
- honeybee/checkdup.py
- honeybee/cli/validate.py
- honeybee/door.py
- honeybee/face.py
- honeybee/model.py
- honeybee/properties.py
- honeybee/room.py
- honeybee/shade.py
- tests/aperture_test.py
- tests/cli_validate_test.py
- tests/door_test.py
- tests/face_test.py
- tests/model_test.py
- tests/room_test.py
- tests/shade_test.py
Now that I have a better sense of how we want to report validation issues, I have refactored all of the checking functions to return strings of error reports rather than a boolean. This means that users get a full report of all the issues found in the model rather than the first exception that was encountered.
I also added a method on the Model class that I imagine I will use in IronPython and is also used by the validation command. This method (and the command) can also be used to check extension attributes.
> feat(validate): Greatly improve validation command

- honeybee/_base.py
- honeybee/aperture.py
- honeybee/cli/validate.py
- honeybee/door.py
- honeybee/face.py
- honeybee/model.py
- honeybee/room.py
- honeybee/shade.py
This should ensure that you don't get errors of 0 vertices unless that is truly what is in the HBJSON file. And all errors shoudl include "display_name[identifier]" so that you can always find the invalid geometry.
> feat(validate): Add several improvements to validation command

- honeybee/_basewithshade.py
- honeybee/aperture.py
- honeybee/door.py
- honeybee/face.py
- honeybee/model.py
- honeybee/room.py
- honeybee/shade.py
It seems we have a couple of workflows that make use of the geometry's orientation now so we should ensure that this Plane information is preserved when we serialize Honeybee objects into JSON.
> feat(plane): Ensure that Face3D plane information is serialized to JSON

- honeybee/room.py
- tests/room_test.py
From my tests, the result of this should align with how EnergyPlus assigns solar enclosures. This makes it possible to match radiant enclosure data back to the original Honeybee Rooms.
> fix(room): Add staticmethod to group rooms by air adjacency

- honeybee/_base.py
- honeybee/_basewithshade.py
- honeybee/aperture.py
- honeybee/door.py
- honeybee/face.py
- honeybee/model.py
- honeybee/room.py
- honeybee/shade.py
- tests/aperture_test.py
- tests/door_test.py
- tests/face_test.py
- tests/model_test.py
- tests/room_test.py
- tests/shade_test.py
This is going to be useful in a lot of cases and I'm surprised we didn't add it earlier.
> fix(geometry): Add min and max properties to all honeybee geometries

- honeybee/face.py
- honeybee/facetype.py
This will ensure that the generated apertures are always aligned with their parent Face normal. It will also generally produce cleaner apertures by removing duplicate vertices before generating apertures.
> fix(face): Improve the reliability of aperture generation methods

- honeybee/model.py
- honeybee/room.py
This is partly trying to address this issue:
https://github.com/ladybug-tools/honeybee-core/issues/509
> fix(room): Add a property to exclude floor area from larger models

- honeybee/aperture.py
- honeybee/door.py
- honeybee/face.py
- honeybee/shade.py
- tests/aperture_test.py
- tests/door_test.py
- tests/face_test.py
- tests/shade_test.py
There have been enough times where I can see that these properties would have saved us some extra code.
> fix(geometry): Add properties for altitude and azimuth

- honeybee/face.py
Method to_dict inside Face class was missing the user_data property.
> Added missing user_data on face to_dict method

- honeybee/_base.py
- honeybee/aperture.py
- honeybee/door.py
- honeybee/face.py
- honeybee/model.py
- honeybee/room.py
- honeybee/shade.py
I realized that we were missing this check. I am also changing the base methods that create the error dictionaries to take the full error code as input to make things more reusable across honeybee extensions.
> fix(validate): Add check to ensure adjacent Faces have matching areas

- honeybee/_base.py
- honeybee/aperture.py
- honeybee/boundarycondition.py
- honeybee/door.py
- honeybee/face.py
- honeybee/model.py
- honeybee/room.py
- honeybee/shade.py
This also changes the behavior of the display_name to be in line with other display names across honeybee extensions.
> fix(name): Ensure that display_name can be reset

- honeybee/room.py
This commit also adds an option to only merge vertical faces of rooms, which is useful in workflows where the model must be coordinated with the Room.horizontal_boundary.
> fix(room): Handle the case of failed coplanar union

- honeybee/face.py
- honeybee/model.py
- honeybee/room.py
I'm also changing the subdivision code in rectangularize apertures to work for concave shapes.
> fix(face): Add an option to merge_all on rectangularize apertures

- honeybee/room.py
I am also changing the grouped_horizontal_boundary to work from the floor faces by default with an optional argument to switch to full Room volumes.
> fix(room): Add properties for honrizontal_floor_boundary

- honeybee/model.py
- honeybee/typing.py
- tests/model_test.py
We'll make use of this in the export process to OpenStudio to give people the option of using display names.
> fix(typing): Add methods for IDing with unique integer

- honeybee/model.py
- honeybee/typing.py
- tests/typing_test.py
I also added a line of code in all functions that clean strings to be usable in identifiers, which will replace spaces with underscores before doing any replacement of special characters. This should help make the identifiers more readable in the destination software.
> fix(model):  Add method to reset and number all object identifiers

- honeybee/model.py
- honeybee/room.py
- tests/model_test.py
This is just an initial commit so that we can get the ball rolling to implement zones in other repos.
> feat(zone): Add a property for Room.zone

- honeybee/model.py
- honeybee/room.py
It seems odd that it took me this long to add it but it is clearly useful.
I am also fixing a bug in the adjacency_grouping method, which can happen when there are missing adjacencies in the input rooms.
> fix(model): Add setters for rooms and all orphaned geometry
